server:
  port: 8080
  
spring:
  elasticsearch:
    # da localhost a localhost
    # uris: http://elasticsearch:9200
    # username: elastic
    # password: XWBQ1rEU7rlw8WLWPYJf
    # da openshift a openshift
    uris: http://elasticsearch:9200
    # da localhost a openshift
    # uris: http://elasticsearch-jeeg-77-dev.apps.rm1.0a51.p1.openshiftapps.com:80
  application:
    name: books-api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true