server:
  port: 8080
  
spring:
  elasticsearch:
    uris: http://elasticsearch-jeeg-77-dev.apps.rm1.0a51.p1.openshiftapps.com
  application:
    name: books-api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true