server:
  port: 8080
  
spring:
  elasticsearch:
    uris: http://elasticsearch.jeeg-77-dev.svc.cluster.local:9200
  application:
    name: books-api

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true